"""Additive analytics, BI, dashboard, staff, and ML metadata models."""
from __future__ import annotations

import uuid
from datetime import date, datetime, time
from decimal import Decimal
from typing import Any

from sqlalchemy import Boolean, CheckConstraint, Date, DateTime, Float, ForeignKey, Index, Integer, Numeric, String, Text, Time, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base, SoftDeleteMixin, TimestampMixin
from app.models.schema import UUIDPK


class DimDate(Base):
    __tablename__="dim_date"
    date_key: Mapped[int]=mapped_column(Integer, primary_key=True); full_date: Mapped[date]=mapped_column(Date, unique=True); year: Mapped[int]=mapped_column(Integer, index=True); quarter: Mapped[int]=mapped_column(Integer); month: Mapped[int]=mapped_column(Integer); month_name: Mapped[str]=mapped_column(String(20)); week: Mapped[int]=mapped_column(Integer); day: Mapped[int]=mapped_column(Integer); day_name: Mapped[str]=mapped_column(String(20)); is_weekend: Mapped[bool]=mapped_column(Boolean); is_holiday: Mapped[bool]=mapped_column(Boolean, default=False); holiday_name: Mapped[str|None]=mapped_column(String(150)); academic_semester: Mapped[str|None]=mapped_column(String(50), index=True); academic_year: Mapped[str|None]=mapped_column(String(20), index=True); fiscal_year: Mapped[int]=mapped_column(Integer); fiscal_quarter: Mapped[int]=mapped_column(Integer); __table_args__=(CheckConstraint("date_key BETWEEN 19000101 AND 29991231"), CheckConstraint("quarter BETWEEN 1 AND 4 AND month BETWEEN 1 AND 12 AND day BETWEEN 1 AND 31"),)
class DimTime(Base):
    __tablename__="dim_time"
    time_key: Mapped[int]=mapped_column(Integer, primary_key=True); full_time: Mapped[time]=mapped_column(Time, unique=True); hour: Mapped[int]=mapped_column(Integer, index=True); minute: Mapped[int]=mapped_column(Integer); second: Mapped[int]=mapped_column(Integer); time_of_day: Mapped[str]=mapped_column(String(20), index=True); is_business_hours: Mapped[bool]=mapped_column(Boolean); is_peak_hours: Mapped[bool]=mapped_column(Boolean); __table_args__=(CheckConstraint("time_key BETWEEN 0 AND 235959"), CheckConstraint("hour BETWEEN 0 AND 23 AND minute BETWEEN 0 AND 59 AND second BETWEEN 0 AND 59"),)

class AIModel(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="ai_models"; provider: Mapped[str]=mapped_column(String(80), index=True); family: Mapped[str]=mapped_column(String(100)); model_name: Mapped[str]=mapped_column(String(120)); version: Mapped[str]=mapped_column(String(80)); release_date: Mapped[date|None]=mapped_column(Date); pricing_input: Mapped[Decimal|None]=mapped_column(Numeric(16,8)); pricing_output: Mapped[Decimal|None]=mapped_column(Numeric(16,8)); token_limit: Mapped[int|None]=mapped_column(Integer); supports_function_call: Mapped[bool]=mapped_column(Boolean, default=False); supports_vision: Mapped[bool]=mapped_column(Boolean, default=False); supports_audio: Mapped[bool]=mapped_column(Boolean, default=False); status: Mapped[str]=mapped_column(String(30), index=True); __table_args__=(UniqueConstraint("provider","model_name","version"), CheckConstraint("pricing_input IS NULL OR pricing_input >= 0"), CheckConstraint("pricing_output IS NULL OR pricing_output >= 0"), CheckConstraint("token_limit IS NULL OR token_limit > 0"),)
class PromptTemplate(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="prompt_templates"; name: Mapped[str]=mapped_column(String(150)); version: Mapped[str]=mapped_column(String(50)); feature: Mapped[str]=mapped_column(String(80), index=True); template: Mapped[str]=mapped_column(Text); created_by: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("users.id", ondelete="SET NULL")); active: Mapped[bool]=mapped_column(Boolean, default=True, index=True); __table_args__=(UniqueConstraint("name","version"),)

class Department(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="departments"; code: Mapped[str]=mapped_column(String(50), unique=True); name: Mapped[str]=mapped_column(String(150), unique=True)
class Role(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="roles"; name: Mapped[str]=mapped_column(String(80), unique=True); description: Mapped[str|None]=mapped_column(Text)
class Permission(UUIDPK, TimestampMixin, Base):
    __tablename__="permissions"; code: Mapped[str]=mapped_column(String(100), unique=True); description: Mapped[str|None]=mapped_column(Text)
class RolePermission(Base):
    __tablename__="role_permissions"; role_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("roles.id", ondelete="CASCADE"), primary_key=True); permission_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("permissions.id", ondelete="CASCADE"), primary_key=True)
class Staff(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="staff"; user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id", ondelete="RESTRICT"), unique=True); employee_code: Mapped[str]=mapped_column(String(50), unique=True); department_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("departments.id", ondelete="SET NULL")); active: Mapped[bool]=mapped_column(Boolean, default=True, index=True); hired_at: Mapped[date|None]=mapped_column(Date)
class StaffRole(Base):
    __tablename__="staff_roles"; staff_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("staff.id", ondelete="CASCADE"), primary_key=True); role_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("roles.id", ondelete="RESTRICT"), primary_key=True); assigned_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), server_default=func.now())
class StaffActivity(UUIDPK, Base):
    __tablename__="staff_activities"; staff_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("staff.id", ondelete="RESTRICT"), index=True); activity_type: Mapped[str]=mapped_column(String(80), index=True); entity_type: Mapped[str|None]=mapped_column(String(80)); entity_id: Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True)); occurred_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), server_default=func.now(), index=True); outcome: Mapped[str]=mapped_column(String(30)); duration_ms: Mapped[int|None]=mapped_column(Integer); metadata_json: Mapped[dict[str,Any]|None]=mapped_column("metadata",JSONB); __table_args__=(CheckConstraint("duration_ms IS NULL OR duration_ms >= 0"), Index("ix_staff_activity_staff_time","staff_id","occurred_at"),)

class Faculty(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="faculties"; code: Mapped[str]=mapped_column(String(50), unique=True); name: Mapped[str]=mapped_column(String(200), unique=True)
class Major(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="majors"; faculty_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("faculties.id", ondelete="RESTRICT")); code: Mapped[str]=mapped_column(String(50), unique=True); name: Mapped[str]=mapped_column(String(200)); __table_args__=(UniqueConstraint("faculty_id","name"),)
class Course(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="courses"; major_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("majors.id", ondelete="SET NULL")); code: Mapped[str]=mapped_column(String(50), unique=True); name: Mapped[str]=mapped_column(String(250)); credits: Mapped[int|None]=mapped_column(Integer)
class StudentAcademicProfile(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="student_academic_profiles"; user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id", ondelete="RESTRICT"), unique=True); faculty_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("faculties.id", ondelete="SET NULL")); major_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("majors.id", ondelete="SET NULL")); academic_year: Mapped[str]=mapped_column(String(20), index=True); student_year: Mapped[int|None]=mapped_column(Integer); current_semester: Mapped[str|None]=mapped_column(String(50)); __table_args__=(CheckConstraint("student_year IS NULL OR student_year BETWEEN 1 AND 10"),)
class CourseEnrollment(UUIDPK, TimestampMixin, Base):
    __tablename__="course_enrollments"; user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id", ondelete="RESTRICT")); course_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("courses.id", ondelete="RESTRICT")); academic_year: Mapped[str]=mapped_column(String(20)); semester: Mapped[str]=mapped_column(String(50)); __table_args__=(UniqueConstraint("user_id","course_id","academic_year","semester"),)
class ReadingRoom(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="reading_rooms"; location_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("library_locations.id", ondelete="RESTRICT")); code: Mapped[str]=mapped_column(String(50), unique=True); name: Mapped[str]=mapped_column(String(150)); floor: Mapped[str|None]=mapped_column(String(30)); zone: Mapped[str|None]=mapped_column(String(80)); capacity: Mapped[int|None]=mapped_column(Integer); map_reference: Mapped[str|None]=mapped_column(String(255)); __table_args__=(CheckConstraint("capacity IS NULL OR capacity >= 0"),)
class LocationTrafficSnapshot(UUIDPK, TimestampMixin, Base):
    __tablename__="location_traffic_snapshots"; date_key: Mapped[int]=mapped_column(ForeignKey("dim_date.date_key", ondelete="RESTRICT")); time_key: Mapped[int]=mapped_column(ForeignKey("dim_time.time_key", ondelete="RESTRICT")); location_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("library_locations.id", ondelete="RESTRICT")); device_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("devices.id", ondelete="SET NULL")); reading_room_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("reading_rooms.id", ondelete="SET NULL")); visitor_count: Mapped[int]=mapped_column(Integer, default=0); occupancy_count: Mapped[int]=mapped_column(Integer, default=0); __table_args__=(UniqueConstraint("date_key","time_key","location_id","device_id","reading_room_id"), CheckConstraint("visitor_count >= 0 AND occupancy_count >= 0"), Index("ix_location_traffic_date_location","date_key","location_id"),)

class DailyFact(UUIDPK, TimestampMixin):
    date_key: Mapped[int]=mapped_column(ForeignKey("dim_date.date_key", ondelete="RESTRICT"), index=True); refreshed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), server_default=func.now()); source_watermark: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class FactDailyLibraryUsage(DailyFact, Base):
    __tablename__="fact_daily_library_usage"; location_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("library_locations.id", ondelete="RESTRICT")); total_sessions: Mapped[int]=mapped_column(Integer, default=0); total_users: Mapped[int]=mapped_column(Integer, default=0); new_users: Mapped[int]=mapped_column(Integer, default=0); anonymous_sessions: Mapped[int]=mapped_column(Integer, default=0); average_session_seconds: Mapped[float|None]=mapped_column(Float); borrow_count: Mapped[int]=mapped_column(Integer, default=0); return_count: Mapped[int]=mapped_column(Integer, default=0); __table_args__=(UniqueConstraint("date_key","location_id"),)
class FactBorrowing(DailyFact, Base):
    __tablename__="fact_borrowing"; book_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("books.id", ondelete="RESTRICT")); location_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("library_locations.id", ondelete="RESTRICT")); faculty_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("faculties.id", ondelete="SET NULL")); borrow_count: Mapped[int]=mapped_column(Integer, default=0); return_count: Mapped[int]=mapped_column(Integer, default=0); overdue_count: Mapped[int]=mapped_column(Integer, default=0); renewal_count: Mapped[int]=mapped_column(Integer, default=0); average_loan_days: Mapped[float|None]=mapped_column(Float); __table_args__=(UniqueConstraint("date_key","book_id","location_id","faculty_id"), Index("ix_fact_borrow_date_location","date_key","location_id"),)
class FactSearch(DailyFact, Base):
    __tablename__="fact_search"; input_method: Mapped[str]=mapped_column(String(40)); search_type: Mapped[str]=mapped_column(String(40)); total_searches: Mapped[int]=mapped_column(Integer, default=0); successful_searches: Mapped[int]=mapped_column(Integer, default=0); zero_result_searches: Mapped[int]=mapped_column(Integer, default=0); clicked_searches: Mapped[int]=mapped_column(Integer, default=0); borrowed_searches: Mapped[int]=mapped_column(Integer, default=0); average_search_time_ms: Mapped[float|None]=mapped_column(Float); __table_args__=(UniqueConstraint("date_key","input_method","search_type"),)
class FactRecommendation(DailyFact, Base):
    __tablename__="fact_recommendation"; ai_model_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("ai_models.id", ondelete="RESTRICT")); trigger_type: Mapped[str]=mapped_column(String(40)); impressions: Mapped[int]=mapped_column(Integer, default=0); clicks: Mapped[int]=mapped_column(Integer, default=0); saves: Mapped[int]=mapped_column(Integer, default=0); attributed_borrows: Mapped[int]=mapped_column(Integer, default=0); recommendation_ctr: Mapped[float|None]=mapped_column(Float); __table_args__=(UniqueConstraint("date_key","ai_model_id","trigger_type"), CheckConstraint("recommendation_ctr IS NULL OR recommendation_ctr BETWEEN 0 AND 1"),)
class FactAIUsage(DailyFact, Base):
    __tablename__="fact_ai_usage"; ai_model_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("ai_models.id", ondelete="RESTRICT")); feature_type: Mapped[str]=mapped_column(String(40)); request_count: Mapped[int]=mapped_column(Integer, default=0); success_count: Mapped[int]=mapped_column(Integer, default=0); error_count: Mapped[int]=mapped_column(Integer, default=0); input_tokens: Mapped[int]=mapped_column(Integer, default=0); output_tokens: Mapped[int]=mapped_column(Integer, default=0); estimated_cost: Mapped[Decimal]=mapped_column(Numeric(18,6), default=0); average_latency_ms: Mapped[float|None]=mapped_column(Float); p95_latency_ms: Mapped[float|None]=mapped_column(Float); __table_args__=(UniqueConstraint("date_key","ai_model_id","feature_type"),)
class FactGame(DailyFact, Base):
    __tablename__="fact_game"; topic: Mapped[str|None]=mapped_column(String(150)); difficulty: Mapped[str|None]=mapped_column(String(50)); started_count: Mapped[int]=mapped_column(Integer, default=0); completed_count: Mapped[int]=mapped_column(Integer, default=0); average_score: Mapped[float|None]=mapped_column(Float); average_response_time_ms: Mapped[float|None]=mapped_column(Float); borrow_after_game_count: Mapped[int]=mapped_column(Integer, default=0); __table_args__=(UniqueConstraint("date_key","topic","difficulty"),)
class FactAuthentication(DailyFact, Base):
    __tablename__="fact_authentication"; method: Mapped[str]=mapped_column(String(40)); device_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("devices.id", ondelete="SET NULL")); attempt_count: Mapped[int]=mapped_column(Integer, default=0); success_count: Mapped[int]=mapped_column(Integer, default=0); retry_count: Mapped[int]=mapped_column(Integer, default=0); average_latency_ms: Mapped[float|None]=mapped_column(Float); average_confidence: Mapped[float|None]=mapped_column(Float); authentication_success_rate: Mapped[float|None]=mapped_column(Float); __table_args__=(UniqueConstraint("date_key","method","device_id"), CheckConstraint("authentication_success_rate IS NULL OR authentication_success_rate BETWEEN 0 AND 1"),)
class FactSurvey(DailyFact, Base):
    __tablename__="fact_survey"; survey_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("surveys.id", ondelete="RESTRICT")); construct_name: Mapped[str]=mapped_column(String(100)); response_count: Mapped[int]=mapped_column(Integer, default=0); average_score: Mapped[float|None]=mapped_column(Float); completion_count: Mapped[int]=mapped_column(Integer, default=0); __table_args__=(UniqueConstraint("date_key","survey_id","construct_name"),)

class BookPopularitySnapshot(UUIDPK, TimestampMixin, Base):
    __tablename__="book_popularity_snapshots"; book_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("books.id", ondelete="RESTRICT")); date_key: Mapped[int]=mapped_column(ForeignKey("dim_date.date_key", ondelete="RESTRICT")); borrow_rank: Mapped[int|None]=mapped_column(Integer); search_rank: Mapped[int|None]=mapped_column(Integer); recommendation_rank: Mapped[int|None]=mapped_column(Integer); score: Mapped[float]=mapped_column(Float); __table_args__=(UniqueConstraint("book_id","date_key"), CheckConstraint("borrow_rank IS NULL OR borrow_rank > 0"), CheckConstraint("search_rank IS NULL OR search_rank > 0"), CheckConstraint("recommendation_rank IS NULL OR recommendation_rank > 0"), Index("ix_book_popularity_date_score","date_key","score"),)

class DashboardMetric(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="dashboard_metrics"; metric_name: Mapped[str]=mapped_column(String(150), unique=True); description: Mapped[str]=mapped_column(Text); formula: Mapped[str]=mapped_column(Text); refresh_frequency: Mapped[str]=mapped_column(String(50)); owner: Mapped[str]=mapped_column(String(150)); category: Mapped[str]=mapped_column(String(80), index=True); source_tables: Mapped[list[str]|None]=mapped_column(JSONB); unit: Mapped[str|None]=mapped_column(String(40)); active: Mapped[bool]=mapped_column(Boolean, default=True)
class AlertRule(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="alert_rules"; name: Mapped[str]=mapped_column(String(150), unique=True); metric_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("dashboard_metrics.id", ondelete="SET NULL")); comparison_operator: Mapped[str]=mapped_column(String(10)); threshold_value: Mapped[Decimal]=mapped_column(Numeric(18,6)); evaluation_window_minutes: Mapped[int]=mapped_column(Integer); severity: Mapped[str]=mapped_column(String(20)); notification_channels: Mapped[list[str]]=mapped_column(JSONB); active: Mapped[bool]=mapped_column(Boolean, default=True); __table_args__=(CheckConstraint("evaluation_window_minutes > 0"),)
class AlertHistory(UUIDPK, Base):
    __tablename__="alert_history"; alert_rule_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("alert_rules.id", ondelete="RESTRICT"), index=True); triggered_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), server_default=func.now(), index=True); observed_value: Mapped[Decimal|None]=mapped_column(Numeric(18,6)); status: Mapped[str]=mapped_column(String(30), index=True); acknowledged_by: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("users.id", ondelete="SET NULL")); acknowledged_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); resolved_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); details: Mapped[dict[str,Any]|None]=mapped_column(JSONB)

class Dashboard(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="dashboards"; name: Mapped[str]=mapped_column(String(150)); dashboard_type: Mapped[str]=mapped_column(String(50), index=True); description: Mapped[str|None]=mapped_column(Text); owner_user_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("users.id", ondelete="SET NULL")); is_public: Mapped[bool]=mapped_column(Boolean, default=False); active: Mapped[bool]=mapped_column(Boolean, default=True); __table_args__=(UniqueConstraint("name","owner_user_id"),)
class DashboardWidget(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="dashboard_widgets"; dashboard_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("dashboards.id", ondelete="CASCADE"), index=True); metric_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("dashboard_metrics.id", ondelete="SET NULL")); title: Mapped[str]=mapped_column(String(150)); widget_type: Mapped[str]=mapped_column(String(50)); data_source: Mapped[str]=mapped_column(String(200)); visualization_config: Mapped[dict[str,Any]|None]=mapped_column(JSONB); refresh_seconds: Mapped[int|None]=mapped_column(Integer); __table_args__=(CheckConstraint("refresh_seconds IS NULL OR refresh_seconds > 0"),)
class WidgetLayout(UUIDPK, TimestampMixin, Base):
    __tablename__="widget_layouts"; widget_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("dashboard_widgets.id", ondelete="CASCADE"), unique=True); x: Mapped[int]=mapped_column(Integer); y: Mapped[int]=mapped_column(Integer); width: Mapped[int]=mapped_column(Integer); height: Mapped[int]=mapped_column(Integer); breakpoint: Mapped[str]=mapped_column(String(20), default="desktop"); __table_args__=(CheckConstraint("x >= 0 AND y >= 0 AND width > 0 AND height > 0"),)
class WidgetFilter(UUIDPK, TimestampMixin, Base):
    __tablename__="widget_filters"; widget_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("dashboard_widgets.id", ondelete="CASCADE")); field_name: Mapped[str]=mapped_column(String(100)); operator: Mapped[str]=mapped_column(String(30)); default_value: Mapped[dict[str,Any]|None]=mapped_column(JSONB); required: Mapped[bool]=mapped_column(Boolean, default=False); __table_args__=(UniqueConstraint("widget_id","field_name"),)
class SavedFilter(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="saved_filters"; user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id", ondelete="CASCADE")); dashboard_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("dashboards.id", ondelete="CASCADE")); name: Mapped[str]=mapped_column(String(150)); filter_values: Mapped[dict[str,Any]]=mapped_column(JSONB); __table_args__=(UniqueConstraint("user_id","dashboard_id","name"),)
class UserDashboardPreference(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="user_dashboard_preferences"; user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id", ondelete="CASCADE")); dashboard_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("dashboards.id", ondelete="CASCADE")); is_default: Mapped[bool]=mapped_column(Boolean, default=False); theme: Mapped[str|None]=mapped_column(String(30)); timezone: Mapped[str|None]=mapped_column(String(50)); preferences: Mapped[dict[str,Any]|None]=mapped_column(JSONB); __table_args__=(UniqueConstraint("user_id","dashboard_id"),)

class MLDataset(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="ml_datasets"; name: Mapped[str]=mapped_column(String(150), unique=True); purpose: Mapped[str]=mapped_column(Text); owner: Mapped[str]=mapped_column(String(150)); source_description: Mapped[str]=mapped_column(Text); privacy_classification: Mapped[str]=mapped_column(String(50)); retention_days: Mapped[int|None]=mapped_column(Integer); __table_args__=(CheckConstraint("retention_days IS NULL OR retention_days > 0"),)
class DatasetVersion(UUIDPK, TimestampMixin, Base):
    __tablename__="dataset_versions"; dataset_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("ml_datasets.id", ondelete="RESTRICT")); version: Mapped[str]=mapped_column(String(50)); storage_reference: Mapped[str]=mapped_column(String(1000)); schema_hash: Mapped[str]=mapped_column(String(64)); row_count: Mapped[int|None]=mapped_column(Integer); extraction_started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); extraction_completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); source_watermark: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); anonymization_method: Mapped[str|None]=mapped_column(String(200)); __table_args__=(UniqueConstraint("dataset_id","version"), CheckConstraint("row_count IS NULL OR row_count >= 0"),)
class MLExperiment(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="ml_experiments"; name: Mapped[str]=mapped_column(String(150), unique=True); objective: Mapped[str]=mapped_column(Text); owner: Mapped[str]=mapped_column(String(150)); status: Mapped[str]=mapped_column(String(30), index=True); tracking_reference: Mapped[str|None]=mapped_column(String(1000))
class FeatureSet(UUIDPK, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__="feature_sets"; name: Mapped[str]=mapped_column(String(150)); version: Mapped[str]=mapped_column(String(50)); description: Mapped[str]=mapped_column(Text); feature_definitions: Mapped[list[dict[str,Any]]]=mapped_column(JSONB); code_reference: Mapped[str|None]=mapped_column(String(1000)); __table_args__=(UniqueConstraint("name","version"),)
class TrainingRun(UUIDPK, TimestampMixin, Base):
    __tablename__="training_runs"; experiment_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("ml_experiments.id", ondelete="RESTRICT")); dataset_version_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("dataset_versions.id", ondelete="RESTRICT")); feature_set_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("feature_sets.id", ondelete="RESTRICT")); ai_model_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("ai_models.id", ondelete="RESTRICT")); started_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); ended_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); status: Mapped[str]=mapped_column(String(30), index=True); parameters: Mapped[dict[str,Any]|None]=mapped_column(JSONB); artifact_reference: Mapped[str|None]=mapped_column(String(1000)); code_version: Mapped[str|None]=mapped_column(String(100)); random_seed: Mapped[int|None]=mapped_column(Integer); __table_args__=(CheckConstraint("ended_at IS NULL OR ended_at >= started_at"),)
class EvaluationMetric(UUIDPK, TimestampMixin, Base):
    __tablename__="evaluation_metrics"; training_run_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("training_runs.id", ondelete="RESTRICT")); metric_name: Mapped[str]=mapped_column(String(100)); metric_value: Mapped[Decimal]=mapped_column(Numeric(20,8)); dataset_split: Mapped[str]=mapped_column(String(30)); evaluation_context: Mapped[dict[str,Any]|None]=mapped_column(JSONB); __table_args__=(UniqueConstraint("training_run_id","metric_name","dataset_split"),)
