from enum import StrEnum


class DBEnum(StrEnum):
    pass


class UserType(DBEnum): STUDENT="STUDENT"; LIBRARIAN="LIBRARIAN"; ADMIN="ADMIN"; RESEARCHER="RESEARCHER"
class AccountStatus(DBEnum): ACTIVE="ACTIVE"; SUSPENDED="SUSPENDED"; CLOSED="CLOSED"; PENDING="PENDING"
class DeviceType(DBEnum): KIOSK="KIOSK"; WEB="WEB"; MOBILE="MOBILE"
class DeviceStatus(DBEnum): ONLINE="ONLINE"; OFFLINE="OFFLINE"; MAINTENANCE="MAINTENANCE"; RETIRED="RETIRED"
class SessionChannel(DBEnum): KIOSK="KIOSK"; WEB="WEB"; MOBILE="MOBILE"
class SessionExitReason(DBEnum): COMPLETED="COMPLETED"; TIMEOUT="TIMEOUT"; USER_EXIT="USER_EXIT"; SYSTEM_ERROR="SYSTEM_ERROR"; BORROW_COMPLETED="BORROW_COMPLETED"
class AuthenticationMethod(DBEnum): FACE="FACE"; STUDENT_CARD="STUDENT_CARD"; CCCD="CCCD"; PASSWORD="PASSWORD"; QR="QR"
class AuthenticationResult(DBEnum): SUCCESS="SUCCESS"; FAILED="FAILED"; UNKNOWN_FACE="UNKNOWN_FACE"; LOW_CONFIDENCE="LOW_CONFIDENCE"; TIMEOUT="TIMEOUT"; ERROR="ERROR"
class InputMethod(DBEnum): VOICE="VOICE"; TEXT="TEXT"; TOUCH="TOUCH"; SYSTEM="SYSTEM"
class SearchType(DBEnum): TITLE="TITLE"; AUTHOR="AUTHOR"; GENRE="GENRE"; KEYWORD="KEYWORD"; QUOTE="QUOTE"; NATURAL_LANGUAGE="NATURAL_LANGUAGE"
class CopyStatus(DBEnum): AVAILABLE="AVAILABLE"; BORROWED="BORROWED"; RESERVED="RESERVED"; LOST="LOST"; MAINTENANCE="MAINTENANCE"
class BorrowingStatus(DBEnum): ACTIVE="ACTIVE"; RETURNED="RETURNED"; OVERDUE="OVERDUE"; LOST="LOST"; CANCELLED="CANCELLED"
class RecommendationTrigger(DBEnum): LOGIN="LOGIN"; SEARCH="SEARCH"; BORROW_HISTORY="BORROW_HISTORY"; GENRE_PREFERENCE="GENRE_PREFERENCE"; WAITING_SCREEN="WAITING_SCREEN"; MANUAL_REQUEST="MANUAL_REQUEST"
class AIFeatureType(DBEnum): NLP="NLP"; SEARCH="SEARCH"; RECOMMENDATION="RECOMMENDATION"; GAME_GENERATION="GAME_GENERATION"; CHAT="CHAT"; RAG_GENERATION="RAG_GENERATION"
class AIRequestStatus(DBEnum): PENDING="PENDING"; SUCCESS="SUCCESS"; FAILED="FAILED"; TIMEOUT="TIMEOUT"
class NotificationStatus(DBEnum): SCHEDULED="SCHEDULED"; SENT="SENT"; DELIVERED="DELIVERED"; FAILED="FAILED"; OPENED="OPENED"
class GameCompletionStatus(DBEnum): STARTED="STARTED"; COMPLETED="COMPLETED"; ABANDONED="ABANDONED"; ERROR="ERROR"
class ResearchStudyStatus(DBEnum): DRAFT="DRAFT"; ACTIVE="ACTIVE"; COMPLETED="COMPLETED"; SUSPENDED="SUSPENDED"
class QuestionType(DBEnum): LIKERT="LIKERT"; NUMERIC="NUMERIC"; MULTIPLE_CHOICE="MULTIPLE_CHOICE"; TEXT="TEXT"; BOOLEAN="BOOLEAN"
