import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { apiClient } from "../services/apiClient";
import { books, categories, documents, mockAnswer, mockFace } from "../services/mockApi";
import type { ChatMessage, FaceResult } from "../types";
import { MetricCard, PageHeader, StatusBadge, UnderDevelopmentCard } from "../components/ui";

export function KioskHome() {
  return <><section className="hero"><div><span className="eyebrow light">TRỢ LÝ THƯ VIỆN THÔNG MINH</span><h1>Xin chào! Hôm nay chúng tôi có thể giúp gì cho bạn?</h1><p>Tìm thông tin, nhận gợi ý sách và chia sẻ trải nghiệm — nhanh chóng ngay tại kiosk.</p><div className="hero-actions"><Link className="button light-button" to="/kiosk/face">Bắt đầu ngay <b>→</b></Link><Link className="text-link" to="/kiosk/chat">Hỏi trợ lý AI</Link></div></div><div className="hero-visual"><span>✦</span><i>AI</i></div></section>
    <div className="section-title"><div><span className="eyebrow">DỊCH VỤ NHANH</span><h2>Bạn muốn làm gì?</h2></div><span className="muted">Chạm vào một dịch vụ để bắt đầu</span></div>
    <div className="action-grid">{[["/kiosk/face","◎","Nhận diện khuôn mặt","Cá nhân hóa trải nghiệm của bạn"],["/kiosk/chat","✦","Hỏi trợ lý AI","Giải đáp nhanh thông tin thư viện"],["/kiosk/books","◇","Gợi ý sách","Khám phá sách theo chủ đề"],["/kiosk/survey","✓","Khảo sát nhanh","Giúp chúng tôi phục vụ tốt hơn"]].map(([to,icon,title,text],i)=><Link className="action-card" to={to} key={to}><span className={`action-icon c${i}`}>{icon}</span><div><h3>{title}</h3><p>{text}</p></div><b>→</b></Link>)}</div>
    <div className="tip"><span>i</span><p><strong>Mẹo nhỏ</strong>Bạn không cần đăng nhập để sử dụng trợ lý AI và gợi ý sách.</p></div></>;
}

export function FaceRecognitionPage() {
  const [result, setResult] = useState<FaceResult | null>(null); const [loading, setLoading] = useState(false);
  async function simulate(scenario: "SUCCESS" | "UNKNOWN_FACE") { setLoading(true); try { setResult(await apiClient.post<FaceResult>("/face/verify/mock", { scenario })); } catch { setResult(mockFace(scenario === "SUCCESS")); } finally { setLoading(false); } }
  return <><PageHeader eyebrow="BƯỚC 1 / 2" title="Nhận diện khuôn mặt" description="Đưa khuôn mặt vào khung hình để hệ thống nhận diện. Camera thật chưa được bật trong bản thử nghiệm." />
    <div className="two-column"><section className="camera-card"><div className="camera-frame"><div className="face-outline">◎</div><span>CAMERA PLACEHOLDER</span></div><div className="button-row"><button onClick={()=>simulate("SUCCESS")} disabled={loading}>Mô phỏng thành công</button><button className="secondary" onClick={()=>simulate("UNKNOWN_FACE")} disabled={loading}>Không nhận diện được</button></div></section>
    <aside className="side-card"><span className="step-icon">◎</span><h2>{result ? result.message : "Sẵn sàng nhận diện"}</h2><p>{result ? `Độ tin cậy: ${Math.round(result.confidence_score * 100)}%` : "Hãy nhìn thẳng vào màn hình và giữ khuôn mặt trong khung."}</p>{result?.user && <div className="profile-result"><strong>{result.user.full_name}</strong><span>{result.user.student_code}</span></div>}{result && <Link className="button" to="/kiosk/chat">Tiếp tục →</Link>}</aside></div></>;
}

export function AIChatPage() {
  const [messages,setMessages]=useState<ChatMessage[]>([{role:"assistant",text:"Xin chào! Tôi là trợ lý AI thư viện. Bạn muốn tìm hiểu điều gì?"}]); const [input,setInput]=useState(""); const [busy,setBusy]=useState(false);
  async function send(e:FormEvent){e.preventDefault(); const q=input.trim(); if(!q)return; setMessages(m=>[...m,{role:"user",text:q}]);setInput("");setBusy(true);try{const data=await apiClient.post<{answer:string}>("/ai/answer/mock",{question:q});setMessages(m=>[...m,{role:"assistant",text:data.answer}]);}catch{setMessages(m=>[...m,{role:"assistant",text:mockAnswer}]);}finally{setBusy(false)}}
  return <div className="chat-page"><PageHeader title="Trợ lý AI thư viện" description="Hỏi về giờ mở cửa, nội quy, dịch vụ và tài liệu thư viện." action={<span className="badge warning">Bản thử nghiệm</span>} /><section className="chat-card"><div className="chat-messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}><span>{m.role==="assistant"?"✦":"BẠN"}</span><p>{m.text}</p></div>)}{busy&&<div className="message assistant"><span>✦</span><p>Đang suy nghĩ…</p></div>}</div><div className="suggestions">{["Thư viện mở cửa lúc mấy giờ?","Làm sao đặt phòng học nhóm?","Gợi ý sách công nghệ"].map(x=><button key={x} onClick={()=>setInput(x)}>{x}</button>)}</div><form className="chat-input" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Nhập câu hỏi của bạn…" aria-label="Câu hỏi"/><button disabled={busy}>Gửi ↑</button></form><small className="mock-note">Bản thử nghiệm chưa kết nối Gemini/RAG thật. Câu trả lời hiện được mô phỏng.</small></section></div>;
}

export function BookSuggestionPage(){const [selected,setSelected]=useState(categories[0]);const shown=books.filter(b=>b.category===selected);return <><PageHeader eyebrow="KHÁM PHÁ" title="Gợi ý sách dành cho bạn" description="Chọn một chủ đề để xem danh sách sách được tuyển chọn từ dữ liệu mô phỏng."/><div className="category-list">{categories.map(c=><button className={c===selected?"active":""} onClick={()=>setSelected(c)} key={c}>{c}</button>)}</div><div className="book-grid">{shown.map((b,i)=><article className="book-card" key={b.title}><div className={`book-cover cover${i}`}>NLU<span>LIBRARY</span></div><div><span className="eyebrow">{b.category}</span><h3>{b.title}</h3><p>{b.author_name}</p><small>Mã liên kết: {b.external_book_id ?? "Chưa có"}</small></div></article>)}</div><div className="tip"><span>i</span><p><strong>Lưu ý</strong>Danh sách chỉ là gợi ý đơn giản, không thay thế danh mục hay trạng thái mượn/trả của thư viện.</p></div></>}

export function SurveyPage(){const nav=useNavigate();const [rating,setRating]=useState(0);const [helped,setHelped]=useState("");async function submit(e:FormEvent){e.preventDefault();try{await apiClient.post("/surveys/survey-2026-01/responses/mock",{answers:{q1:rating,q2:helped}})}catch{/* Mock fallback needs no persistence. */}nav("/kiosk/thanks")}return <><PageHeader eyebrow="CHỈ MẤT 1 PHÚT" title="Bạn thấy trải nghiệm hôm nay thế nào?" description="Phản hồi của bạn giúp chúng tôi cải thiện trợ lý thư viện."/><form className="survey-card" onSubmit={submit}><fieldset><legend>Bạn có hài lòng với câu trả lời của AI không?</legend><div className="rating">{[1,2,3,4,5].map(n=><button type="button" className={n<=rating?"selected":""} onClick={()=>setRating(n)} key={n}>★<small>{n}</small></button>)}</div></fieldset><fieldset><legend>AI có giúp bạn giảm thời gian hỏi lễ tân không?</legend><div className="choice-row">{["Có","Không","Chưa chắc"].map(v=><button type="button" className={helped===v?"selected":""} onClick={()=>setHelped(v)} key={v}>{v}</button>)}</div></fieldset><button disabled={!rating||!helped}>Gửi phản hồi</button></form></>}
export function ThankYouPage(){return <section className="thank-you"><div>✓</div><span className="eyebrow">PHẢN HỒI ĐÃ ĐƯỢC GHI NHẬN</span><h1>Cảm ơn bạn!</h1><p>Ý kiến của bạn là động lực để thư viện phục vụ tốt hơn mỗi ngày.</p><Link className="button" to="/kiosk">Về màn hình chính</Link></section>}

const metrics=[["◫","Tổng lượt sử dụng","1.284","+12,5% so với tháng trước"],["◎","Người dùng đã nhận diện","947","73,8% tổng lượt"],["?","Tổng câu hỏi","3.260","2,5 câu mỗi phiên"],["✦","Câu trả lời AI","3.198","98,1% phản hồi thành công"],["✓","Khảo sát đã gửi","486","37,9% tỷ lệ phản hồi"],["★","Điểm hài lòng","4,6 / 5","Rất hài lòng"]];
export function AdminDashboardPage(){return <><PageHeader eyebrow="TỔNG QUAN HỆ THỐNG" title="Chào buổi sáng, Quản trị viên" description="Theo dõi hoạt động của AI Library Receptionist trong hôm nay." action={<button>Xuất báo cáo</button>}/><div className="metric-grid">{metrics.map(m=><MetricCard key={m[1]} icon={m[0]} label={m[1]} value={m[2]} detail={m[3]}/>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Hoạt động 7 ngày qua</h2><span className="badge success">Dữ liệu mô phỏng</span></div><div className="bar-chart">{[45,62,51,78,69,88,74].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>{["T2","T3","T4","T5","T6","T7","CN"][i]}</span></div>)}</div></section><section className="panel"><div className="panel-head"><h2>Trạng thái tính năng</h2></div>{[["Cơ sở dữ liệu","Hoàn thành","success"],["FaceID","Chỉ mô phỏng","warning"],["Trợ lý AI","Chỉ mô phỏng","warning"],["RAG","Chưa triển khai","danger"]].map(x=><div className="status-row" key={x[0]}><span>{x[0]}</span><span className={`badge ${x[2]}`}>{x[1]}</span></div>)}</section></div></>}

export function KnowledgeUploadPage(){return <><PageHeader eyebrow="QUẢN TRỊ TRI THỨC" title="Tài liệu tri thức" description="Quản lý nguồn thông tin sẽ được trợ lý AI sử dụng để trả lời." action={<button>＋ Tải tài liệu</button>}/><section className="upload-zone"><span>⇧</span><h3>Kéo thả tài liệu vào đây</h3><p>PDF, Word, Excel, Image, Web Link hoặc Text</p><button className="secondary">Chọn tệp (mô phỏng)</button></section><section className="panel table-panel"><div className="panel-head"><h2>Tài liệu gần đây</h2><span>{documents.length} tài liệu</span></div><div className="data-table">{documents.map(d=><div className="table-row" key={d.id}><span className="file-icon">▤</span><div><strong>{d.title}</strong><small>{d.source_type} · cập nhật gần đây</small></div><StatusBadge status={d.status}/><button className="icon-button">•••</button></div>)}</div></section></>}
export function ConversationLogsPage(){return <><PageHeader title="Nhật ký hội thoại" description="Theo dõi các phiên hỏi đáp mô phỏng gần đây."/><section className="panel">{[["Phạm Hoàng Tuấn Tú","08:42","Thư viện mở cửa lúc mấy giờ?","Đã trả lời"],["Khách ẩn danh","09:16","Phòng học nhóm ở đâu?","Đã trả lời"],["Nguyễn Thảo Vy","10:03","Gợi ý sách kỹ năng mềm","Đang xử lý"]].map(x=><div className="log-row" key={x[1]}><div className="avatar small">{x[0][0]}</div><div><strong>{x[0]}</strong><small>{x[2]}</small></div><time>{x[1]}</time><span className={`badge ${x[3]==="Đã trả lời"?"success":"warning"}`}>{x[3]}</span></div>)}</section></>}
export function UserManagementPage(){return <><PageHeader title="Người dùng" description="Danh sách người dùng mô phỏng phục vụ kiểm thử giao diện."/><section className="panel"><div className="table-head"><span>Mã SV / Họ tên</span><span>Khoa / Ngành</span><span>Khóa học</span><span>Trạng thái</span></div>{[["ITCSIU24092","Phạm Hoàng Tuấn Tú","CNTT · Khoa học máy tính","2024 · Năm 3"],["NLU23018","Nguyễn Thảo Vy","Kinh tế · Quản trị kinh doanh","2023 · Năm 4"]].map(x=><div className="user-row" key={x[0]}><div><strong>{x[1]}</strong><small>{x[0]}</small></div><span>{x[2]}</span><span>{x[3]}</span><span className="badge success">Hoạt động</span></div>)}</section></>}
export function SurveyManagementPage(){return <><PageHeader title="Quản lý khảo sát" description="Xem khảo sát đang hoạt động và trạng thái câu hỏi."/><section className="panel survey-summary"><span className="badge success">Đang hoạt động</span><h2>Khảo sát trải nghiệm kiosk</h2><p>4 câu hỏi · 486 phản hồi mô phỏng</p></section><UnderDevelopmentCard title="Chỉnh sửa bộ câu hỏi" backHref="/admin" backLabel="Về Tổng quan"/></>}
export function ReportsPage(){return <><PageHeader title="Báo cáo tổng quan" description="Các chỉ số vận hành cơ bản của kiosk trong giai đoạn thử nghiệm."/><div className="metric-grid compact">{metrics.slice(0,4).map(m=><MetricCard key={m[1]} icon={m[0]} label={m[1]} value={m[2]} detail={m[3]}/>)}</div><div className="dashboard-grid"><section className="panel placeholder-chart"><h2>Phân bố câu hỏi theo chủ đề</h2><div><i/><i/><i/><i/></div><p>Biểu đồ chính thức sẽ được tích hợp khi có dữ liệu thật.</p></section><UnderDevelopmentCard title="Báo cáo chuyên sâu" backHref="/admin" backLabel="Về Tổng quan"/></div></>}
export function NotFoundPage(){return <UnderDevelopmentCard title="Không tìm thấy trang" description="Đường dẫn bạn vừa mở không tồn tại hoặc đã được di chuyển."/>}
