import type { KioskState } from "../types/kiosk";
const transitions: Partial<Record<KioskState, KioskState[]>> = {
  IDLE: ["PRESENCE_DETECTED"],
  PRESENCE_DETECTED: ["WAKE_UP"], WAKE_UP: ["GREETING"], GREETING: ["CAMERA_PREPARING"],
  CAMERA_PREPARING: ["FACE_TRACKING", "FACE_RECOGNIZING", "UNKNOWN_FACE"],
  FACE_TRACKING: ["FACE_RECOGNIZING", "UNKNOWN_FACE", "FACE_RECOGNIZED"],
  FACE_RECOGNIZING: ["FACE_TRACKING", "UNKNOWN_FACE", "FACE_RECOGNIZED"],
  UNKNOWN_FACE: ["REGISTER", "FACE_TRACKING", "FACE_RECOGNIZED"],
  REGISTER: ["REGISTER_PROCESSING", "UNKNOWN_FACE"],
  REGISTER_PROCESSING: ["REGISTER", "REGISTER_SUCCESS"], REGISTER_SUCCESS: ["WELCOME"],
  FACE_RECOGNIZED: ["STOP_CAMERA"], STOP_CAMERA: ["WELCOME"], WELCOME: ["AI_GREETING"],
  AI_GREETING: ["LISTENING", "VOICE_LISTENING"],
  VOICE_LISTENING: ["USER_SPEAKING", "LISTENING", "PROCESSING"], LISTENING: ["USER_SPEAKING", "PROCESSING", "VOICE_LISTENING"],
  USER_SPEAKING: ["PROCESSING", "VOICE_LISTENING", "LISTENING"], PROCESSING: ["AI_SPEAKING"],
  AI_SPEAKING: ["VOICE_LISTENING", "LISTENING"], SURVEY: ["THANK_YOU"], THANK_YOU: ["RETURN_IDLE"], RETURN_IDLE: ["IDLE"],
  BOOK_SUGGESTION: ["VOICE_LISTENING"],
};
export function canTransition(from: KioskState, to: KioskState) {
  if (to === "IDENTITY_CONFIRMING") return ["CAMERA_PREPARING", "FACE_TRACKING", "FACE_RECOGNIZING", "UNKNOWN_FACE"].includes(from);
  if (from === to) return true;
  if (["ERROR", "RETURN_IDLE"].includes(to)) return true;
  if (["SURVEY", "THANK_YOU"].includes(to) && from !== "IDLE") return true;
  return transitions[from]?.includes(to) ?? false;
}
